development:
  adapter: postgresql
  encoding: unicode
  database: viddit_development
  pool: 5
  username: <%= ENV['USER'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: viddit_test
  pool: 5
  username: <%= ENV['USER'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: viddit_production
  pool: 5
  username: <%= ENV['USER'] %>
